name: Lint and Test Helm Charts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Helm
          uses: azure/setup-helm@v4

        - name: Set up python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Run pre-commit
          uses: pre-commit/action@v3.0.1
          with:
            extra_args: helm-docs-built

        - name: Set up chart-testing
          uses: helm/chart-testing-action@v2

        - name: Run chart-testing (list-changed)
          id: list-changed
          run: |
            changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
            if [[ -n "$changed" ]]; then
              echo "changed=true" >> "$GITHUB_OUTPUT"
            fi

        - name: Run chart-testing
          if: steps.list-changed.outputs.changed == 'true'
          run: ct lint --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false
